# AUTOGENERATED! DO NOT EDIT! File to edit: 15_django_asgi.ipynb (unless otherwise specified).

__all__ = ['application']

# Cell
# dont_test
"""
ASGI config for will_it_saturate project.
It exposes the ASGI callable as a module-level variable named ``application``.
For more information on this file, see
https://docs.djangoproject.com/en/3.1/howto/deployment/asgi/
"""

import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "will_it_saturate.django.settings")

import django

django.setup(set_prefix=False)

from .handlers import AsyncFileASGIHandler

application = AsyncFileASGIHandler()

# serve files via async file response
from .views import set_serve_file_to_async