# AUTOGENERATED! DO NOT EDIT! File to edit: 15_django_async_settings.ipynb (unless otherwise specified).

__all__ = ['ROOT_URLCONF']

# Cell
# dont_test

from .settings import *

ROOT_URLCONF = "will_it_saturate.django.async_urls"