# AUTOGENERATED! DO NOT EDIT! File to edit: 15_django_async_urls.ipynb (unless otherwise specified).

__all__ = ['urlpatterns']

# Cell

from django.urls import path
from . import views

urlpatterns = [
    path("<str:base>/<str:path>/<int:num>", views.serve_file_async),
]