# AUTOGENERATED! DO NOT EDIT! File to edit: 14_django_async_file_response.ipynb (unless otherwise specified).

__all__ = ['AsyncFileResponse']

# Cell
import time
import aiofiles

from django.http import FileResponse


class AsyncFileResponse(FileResponse):
    async_file_response = True

    def __init__(self, *args, **kwargs):
        # open_file = args[0]
        # print(f"starting to serve: {open_file.name}")
        # self.open_file_name = args[0].name
        self.started_serving = time.perf_counter()
        self.chunk_size = kwargs.get("chunk_size", 4096)
        self.async_file = None
        self.more_body = True
        super().__init__(*args, **kwargs)

    def __aiter__(self):
        return self

    async def __anext__(self):
        if self.async_file is None:
            self.async_file = await aiofiles.open(self.filename, mode="rb")
        while self.more_body:
            chunk = await self.async_file.read(self.chunk_size)
            self.more_body = len(chunk) == self.chunk_size
            return self.more_body, chunk
        elapsed = time.perf_counter() - self.started_serving
        print(f"elapsed: {elapsed} for {self.filename}")
        await self.async_file.close()
        raise StopAsyncIteration