# AUTOGENERATED! DO NOT EDIT! File to edit: 15_django_settings.ipynb (unless otherwise specified).

__all__ = ['BASE_DIR', 'SECRET_KEY', 'DEBUG', 'ALLOWED_HOSTS', 'INSTALLED_APPS', 'MIDDLEWARE', 'ROOT_URLCONF',
           'TEMPLATES', 'WSGI_APPLICATION', 'DATABASES', 'AUTH_PASSWORD_VALIDATORS', 'LANGUAGE_CODE', 'TIME_ZONE',
           'USE_I18N', 'USE_L10N', 'USE_TZ', 'STATIC_URL', 'LOGGING', 'DJANGO_AWS_ACCESS_KEY_ID',
           'DJANGO_AWS_SECRET_ACCESS_KEY', 'DJANGO_AWS_REGION', 'DJANGO_AWS_STORAGE_BUCKET_NAME', 'MINIO_ENDPOINT_URL']

# Cell
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path().resolve()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "b1y4apm267-am-ya1^i=7227z#hz=8y9ca4am*p_&iclf6wlu4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
]

MIDDLEWARE = []

ROOT_URLCONF = "will_it_saturate.django.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "will_it_saturate.django.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "django.db",
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"

# logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# AWS S3 / MinIO settings
DJANGO_AWS_ACCESS_KEY_ID = "minioadmin"
DJANGO_AWS_SECRET_ACCESS_KEY = "minioadmin"
DJANGO_AWS_REGION = "us-west-2"
DJANGO_AWS_STORAGE_BUCKET_NAME = "wis"
MINIO_ENDPOINT_URL = "http://localhost:9000"