# AUTOGENERATED! DO NOT EDIT! File to edit: 01_django_views.ipynb (unless otherwise specified).

__all__ = ['serve_file']

# Cell
from pathlib import Path

from django.http import JsonResponse
from django.http import FileResponse


async def serve_file(request, base, path, num):
    file_path = Path(base) / path / str(num)
    # return JsonResponse({"file_path": file_path})
    return FileResponse(file_path.open("rb"))