# AUTOGENERATED! DO NOT EDIT! File to edit: 15_django_wsgi.ipynb (unless otherwise specified).

__all__ = ['create_app_filesystem', 'create_app_minio', 'application']

# Cell
import os

from django.conf import settings
from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "will_it_saturate.django.settings")

from . import urls


def create_app_filesystem():
    urls.urlpatterns = urls.urlpatterns_sync_filesystem
    return get_wsgi_application()


def create_app_minio():
    urls.urlpatterns = urls.urlpatterns_sync_minio
    return get_wsgi_application()


application = get_wsgi_application()