# AUTOGENERATED! DO NOT EDIT! File to edit: 32_control_cli.ipynb (unless otherwise specified).

__all__ = ['run_server']

# Cell

import uvicorn


def run_server():
    print("starting control server")
    uvicorn.run(
        "will_it_saturate.control.main:app",
        host="0.0.0.0",
        port=8100,
        log_level="info",
        reload=False,
    )