# AUTOGENERATED! DO NOT EDIT! File to edit: 02_control_server.ipynb (unless otherwise specified).

__all__ = ['read_root', 'create_epoch', 'app']

# Cell

from pathlib import Path
from pydantic import BaseModel

from fastapi import FastAPI

from ..core import Epoch, FilesystemCreator

app = FastAPI()


@app.get("/")
def read_root():
    return {"Hello": "World/Control"}


@app.post("/epochs/")
def create_epoch(epoch: Epoch):
    print(epoch)
    epoch.file_creator = FilesystemCreator()
    epoch.create_files()
    return epoch
