# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Host": "00_host.ipynb",
         "serve_file": "01_fastapi_views.ipynb",
         "read_root": "27_control_server.ipynb",
         "get_file_urls": "01_fastapi_views.ipynb",
         "app": "27_control_server.ipynb",
         "calculate_checksum": "01_file.ipynb",
         "checksum_for_path": "01_file.ipynb",
         "create_via_filesystem": "01_file.ipynb",
         "BenchmarkFile": "01_file.ipynb",
         "FILE_CREATORS": "01_file.ipynb",
         "NginxDockerServer": "02_docker_servers.ipynb",
         "FastAPIUvicornServer": "02_local_servers.ipynb",
         "DjangoGunicornWSGIServer": "02_local_servers.ipynb",
         "BaseServer": "03_servers.ipynb",
         "BaseClient": "04_clients.ipynb",
         "Epoch": "05_epochs.ipynb",
         "convert_size": "06_results.ipynb",
         "Result": "06_results.ipynb",
         "BaseRepository": "07_repositories.ipynb",
         "InMemoryRepository": "07_repositories.ipynb",
         "get_macos_machine_id": "25_core.ipynb",
         "get_linux_machine_id": "25_core.ipynb",
         "get_machine_id": "25_core.ipynb",
         "Benchmark": "25_core.ipynb",
         "create_epoch": "27_control_server.ipynb",
         "create_server": "27_control_server.ipynb",
         "list_servers": "27_control_server.ipynb",
         "machine": "27_control_server.ipynb",
         "servers": "27_control_server.ipynb",
         "ControlClient": "28_control_client.ipynb",
         "HttpxClient": "30_benchmark_clients.ipynb",
         "run_httpx": "30_benchmark_clients.ipynb",
         "counter": "30_benchmark_clients.ipynb",
         "request": "30_benchmark_clients.ipynb",
         "AioHttpResponse": "30_benchmark_clients.ipynb",
         "AioHttpClient": "30_benchmark_clients.ipynb",
         "WrkClient": "30_benchmark_clients.ipynb",
         "SqliteRepository": "40_persistence.ipynb"}

modules = ["hosts.py",
           "django/views.py",
           "fastapi/main.py",
           "files.py",
           "server.py",
           "servers.py",
           "clients.py",
           "epochs.py",
           "results.py",
           "repositories.py",
           "old_core.py",
           "control/main.py",
           "control/client.py",
           "client.py",
           "persistence.py"]

doc_url = "https://ephes.github.io/will_it_saturate/"

git_url = "https://github.com/ephes/will_it_saturate/tree/main/"

def custom_doc_links(name): return None
