# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_with_urandom": "01_create_files.ipynb",
         "Creator": "01_create_files.ipynb"}

modules = ["files.py"]

doc_url = "https://ephes.github.io/will_it_saturate/"

git_url = "https://github.com/ephes/will_it_saturate/tree/main/"

def custom_doc_links(name): return None
