# AUTOGENERATED! DO NOT EDIT! File to edit: 04_clients.ipynb (unless otherwise specified).

__all__ = ['BaseClient']

# Cell

from pydantic import BaseModel

from .files import calculate_checksum


class BaseClient(BaseModel):
    name: str = "base_client"

    def verify_checksums(self, epoch, responses):
        checksum_lookup = {}
        for response in responses:
            url = str(response.url)
            checksum_lookup[url] = calculate_checksum(response.content)

        for bf, url in zip(epoch.files, epoch.urls):
            looked_up_checksum = checksum_lookup.get(url, None)
            if bf.checksum != looked_up_checksum:
                print(bf.checksum, looked_up_checksum, url)

            assert bf.checksum == looked_up_checksum