# AUTOGENERATED! DO NOT EDIT! File to edit: 01_config.ipynb (unless otherwise specified).

__all__ = ['Settings', 'settings']

# Cell

from pydantic import BaseSettings, Field


class Settings(BaseSettings):
    minio_endpoint: str = Field(default="127.0.0.1:9000", end="MINIO_ENDPOINT")
    minio_access_key: str = Field(default="minioadmin", env="MINIO_ACCESS_KEY")
    minio_secret_key: str = Field(default="minioadmin", env="MINIO_SECRET_KEY")
    minio_bucket: str = Field(default="wis", enf="MINIO_BUCKET_NAME")

    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"


settings = Settings()