# AUTOGENERATED! DO NOT EDIT! File to edit: 01_create_files.ipynb (unless otherwise specified).

__all__ = ['Creator']

# Cell

class Creator:
    """
    Create files used for benchmark.
    """
    def __init__(self, bandwidth=10**9 / 8, duration=30, file_size=100 * 1024 * 1024):
        self.bandwidth = bandwidth
        self.duration = duration
        self.file_size = file_size

