# AUTOGENERATED! DO NOT EDIT! File to edit: 03_create_files_old.ipynb (unless otherwise specified).

__all__ = ['create_with_urandom', 'Creator']

# Cell


def create_with_urandom(path, size):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as f:
        f.write(os.urandom(size))


class Creator:
    """
    Create files used for benchmark.

    All sizes are in byte, durations in seconds.
    """
    def __init__(self, bandwidth=10**9 / 8, duration=30, file_size=10 ** 6 * 100):
        self.bandwidth = bandwidth
        self.duration = duration
        self.file_size = file_size
        self.complete_size = duration * bandwidth

    @property
    def number_of_files(self):
        return math.ceil(self.complete_size / self.file_size)

    @property
    def root(self):
        return Path("data") / f"{self.bandwidth}_{self.duration}_{self.file_size}"

    def create_file(self, num, file_creator):
        root = self.root
        file_path = root / str(num)
        file_creator(file_path, self.file_size)

    def create_files(self, file_creator=create_with_urandom):
        for num in range(self.number_of_files):
            self.create_file(num, file_creator)