# AUTOGENERATED! DO NOT EDIT! File to edit: 02_file.ipynb (unless otherwise specified).

__all__ = ['calculate_checksum', 'checksum_for_path', 'create_via_filesystem', 'build_create_via_minio',
           'BenchmarkFile', 'FILE_CREATORS']

# Cell

import os
import io
import hashlib

from minio import Minio
from pathlib import Path
from typing import Optional
from pydantic import BaseModel


def calculate_checksum(content):
    return hashlib.md5(content).hexdigest()


def checksum_for_path(path):
    with path.open("rb") as f:
        checksum = calculate_checksum(f.read())
    return checksum


def create_via_filesystem(path, size):
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        with path.open("wb") as f:
            f.write(os.urandom(size))
    return checksum_for_path(path)


def build_create_via_minio():
    client = Minio("127.0.0.1:9000", "minioadmin", "minioadmin", secure=False)
    bucket_name = "wis"
    found = client.bucket_exists(bucket_name)
    if not found:
        client.make_bucket(bucket_name)

    def create_via_minio(path, size):
        print("via minio:", path, size)
        data = os.urandom(size)

        result = client.put_object(
            bucket_name,
            str(path),
            io.BytesIO(data),
            size,
        )
        return calculate_checksum(data)

    return create_via_minio


FILE_CREATORS = {"filesystem": create_via_filesystem, "minio": build_create_via_minio()}


class BenchmarkFile(BaseModel):
    number: int
    base_path: str
    size: int
    data_root: str = "data"
    hostname: str = "localhost"
    port: int = 8000
    checksum: Optional[str] = None
    creator_name: str = "filesystem"

    @property
    def filesystem_path(self):
        return Path(self.data_root) / self.base_path / str(self.number)

    def get_or_create(self):
        create = FILE_CREATORS.get(self.creator_name)
        self.checksum = create(self.filesystem_path, self.size)

    @property
    def path(self):
        return f"{self.data_root}/{self.base_path}/{self.number}"

    @property
    def host(self):
        return f"http://{self.hostname}:{self.port}"

    @property
    def url(self):
        return f"{self.host}/{self.path}"