# AUTOGENERATED! DO NOT EDIT! File to edit: 00_host.ipynb (unless otherwise specified).

__all__ = ['Host']

# Cell

from pydantic import BaseModel


class Host(BaseModel):
    name: str
    port: int