# AUTOGENERATED! DO NOT EDIT! File to edit: 01_serve_files.ipynb (unless otherwise specified).

__all__ = ['read_root', 'get_file_urls', 'serve_file', 'app']

# Cell

from pathlib import Path

from fastapi import FastAPI
from fastapi.responses import FileResponse

# Cell

app = FastAPI()


@app.get("/")
def read_root():
    return {"Hello": "World"}


@app.get("/pathinfo/{base_dir}")
def get_file_urls(base_dir: str):
    pass


@app.get("/files/{path}/{num}")
async def serve_file(path: str, num: int):
    file_path = str(Path("./data/") / path / str(num))
    return FileResponse(file_path)