# AUTOGENERATED! DO NOT EDIT! File to edit: 02_serve_files.ipynb (unless otherwise specified).

__all__ = ['read_root', 'serve_file', 'app']

# Cell

from fastapi import FastAPI

# Cell

app = FastAPI()


@app.get("/")
def read_root():
    return {"Hello": "World"}


@app.get("/files/{base_dir}/{num}")
def serve_file(base_dir: str, num: int):
    return {"base_dir": base_dir, "num": num}