# AUTOGENERATED! DO NOT EDIT! File to edit: 71_sqlite_repository.ipynb (unless otherwise specified).

__all__ = ['BaseRepository', 'InMemoryRepository', 'dict_factory', 'SqliteRepository']

# Cell

from typing import Any
from pydantic import BaseModel
from collections import defaultdict


class BaseRepository(BaseModel):
    session: Any = None

    def get_result(self, benchmark, result):
        pass

    def add_result(self, benchmark, result):
        pass


class InMemoryRepository(BaseRepository):
    results: dict = defaultdict(dict)

    def get_result(self, benchmark, result):
        return self.results.get(benchmark, {}).get(result, result)

    def add_result(self, benchmark, result):
        self.results[benchmark][result] = result

# Cell

import json
import sqlite3

from .hosts import HostDetails


def dict_factory(cursor, row):
    d = {}
    for idx, col in enumerate(cursor.description):
        d[col[0]] = row[idx]
    return d


class SqliteRepository(BaseRepository):
    connection: sqlite3.Connection

    class Config:
        arbitrary_types_allowed = True

    def execute_stmt(self, stmt, ignore_error=False):
        cursor = self.connection.cursor()
        try:
            cursor.execute(stmt)
        except sqlite3.OperationalError as exc:
            if not ignore_error:
                raise (exc)

    def create_host_table(self):
        stmt = """
            create table host (
                host_id INTEGER PRIMARY KEY,
                created DATE DEFAULT (datetime('now','localtime')),
                machine_id TEXT NOT NULL UNIQUE,
                data TEXT NOT NULL
            )
        """
        self.execute_stmt(stmt, ignore_error=True)

    def create_result_table(self):
        stmt = """
            create table result (
                result_id INTEGER PRIMARY KEY,
                server_host_id integer not NULL,
                client_host_id integer not NULL,
                created DATE DEFAULT (datetime('now','localtime')),
                server text not NULL,
                client text not NULL,
                file_size integer not NULL,
                complete_size integer not NULL,
                elapsed real not NULL,
                FOREIGN KEY(server_host_id) REFERENCES host(host_id)
                FOREIGN KEY(client_host_id) REFERENCES host(host_id)
            )
        """
        self.execute_stmt(stmt, ignore_error=True)

    def create_tables(self):
        self.create_host_table()
        self.create_result_table()

    def get_machine_to_host_id(self, machine_ids):
        question_marks = ", ".join(["?" for _ in machine_ids])
        stmt = f"""
            select host_id, machine_id
              from host
             where machine_id in ({question_marks})
        """
        cursor = self.connection.cursor()
        cursor.execute(stmt, machine_ids)
        rows = cursor.fetchall()
        return {row["machine_id"]: row["host_id"] for row in rows}

    def insert_host_details(self, host_details):
        stmt = """
            insert into host (machine_id, data)
            values (?, ?)
        """
        cursor = self.connection.cursor()
        try:
            cursor = cursor.execute(
                stmt, [host_details.machine_id, host_details.json()]
            )
        except sqlite3.IntegrityError as e:
            pass
        self.connection.commit()
        return cursor.rowcount

    def get_host_id_to_host_details(self, host_ids):
        # fetch matching host details from database
        question_marks = ", ".join(["?" for _ in host_ids])
        stmt = f"""
            select *
              from host
             where host_id in ({question_marks})
        """
        cursor = self.connection.cursor()
        cursor.execute(stmt, host_ids)
        rows = cursor.fetchall()
        if len(rows) == 0:
            return []

        # build host_id_to_host_details lookup
        host_id_to_host_details = {}
        for row in rows:
            kwargs = json.loads(row["data"])
            host_id_to_host_details[row["host_id"]] = HostDetails(**kwargs)
        return host_id_to_host_details

    def get_results(self):
        stmt = """
            select *
              from result
        """
        cursor = self.connection.cursor()
        cursor.execute(stmt)
        rows = cursor.fetchall()
        return rows

    def get_or_create_hosts_from_result(self, result):
        machine_id_to_server_details = {
            result.server_details.machine_id: result.server_details,
            result.client_details.machine_id: result.client_details,
        }
        machine_ids = list(machine_id_to_server_details.keys())
        machine_to_host_id = self.get_machine_to_host_id(machine_ids)
        for machine_id, host_detail in machine_id_to_server_details.items():
            if machine_id not in machine_to_host_id:
                self.insert_host_details(host_detail)
        return self.get_machine_to_host_id(machine_ids)

    def add_result(self, result):
        machine_to_host_id = self.get_or_create_hosts_from_result(result)
        result_row = {
            "server_host_id": machine_to_host_id[result.server_details.machine_id],
            "client_host_id": machine_to_host_id[result.client_details.machine_id],
            "server": result.server.json(),
            "client": result.client.json(),
            "file_size": result.file_size,
            "complete_size": result.complete_size,
            "elapsed": result.elapsed,
        }
        columns = list(result_row.keys())
        columns_str = ",".join(columns)
        values_str = ",".join(["?" for c in columns])

        stmt = f"""
            insert into result ({columns_str})
            values ({values_str})
        """
        cursor = self.connection.cursor()

        values = [result_row[c] for c in columns]
        try:
            cursor = cursor.execute(stmt, values)
        except sqlite3.IntegrityError as e:
            pass
        self.connection.commit()
        return cursor.rowcount

    @classmethod
    def build_repository(cls, database_name):
        conn = sqlite3.connect(database_name)
        conn.row_factory = dict_factory
        repo = cls(connection=conn)
        repo.create_tables()
        return repo