# AUTOGENERATED! DO NOT EDIT! File to edit: 07_repositories.ipynb (unless otherwise specified).

__all__ = ['BaseRepository', 'InMemoryRepository']

# Cell

import os
import math
import json
import hashlib

import pandas as pd

from pathlib import Path
from urllib.parse import urljoin
from typing import Optional, Callable, Any

from pydantic import BaseModel

from .epochs import Epoch
from .results import Result
from .servers import BaseServer
from .clients import BaseClient
from .files import BenchmarkFile, FILE_CREATORS

# Cell

from collections import defaultdict


class BaseRepository(BaseModel):
    session: Any = None

    def get_result(self, benchmark, result):
        pass

    def add_result(self, benchmark, result):
        pass


class InMemoryRepository(BaseRepository):
    results: dict = defaultdict(dict)

    def get_result(self, benchmark, result):
        return self.results.get(benchmark, {}).get(result, result)

    def add_result(self, benchmark, result):
        self.results[benchmark][result] = result