# AUTOGENERATED! DO NOT EDIT! File to edit: 03_servers.ipynb (unless otherwise specified).

__all__ = ['BaseServer']

# Cell

from pydantic import BaseModel

from .files import BenchmarkFile

# Cell


class BaseServer(BaseModel):
    protocol: str = "http"
    name: str = "base_server"
    host: str = "localhost"
    port: int = 8000

    def start(self):
        pass

    def stop(self):
        pass

    def is_running(self):
        return False

    def file_to_url(self, file: BenchmarkFile):
        return f"{self.protocol}://{self.host}:{self.port}/{file.path}"